"""add embed column to song

Revision ID: 009175297a09
Revises: d07590dfe6f2
Create Date: 2024-08-08 11:23:50.840196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009175297a09'
down_revision = 'd07590dfe6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_embed', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs_table', schema=None) as batch_op:
        batch_op.drop_column('youtube_embed')

    # ### end Alembic commands ###
